### Обучающая и тестовая выборки

- В качестве обучающей выборки будем использовать наборы, полученные при помощи train_test_split из scikit-learn.
- Конечно, алгоритм может работать с многомерным пространством, но для удобства демонстраиции алгоритма мы используем двухмерный набор данных.
- Если разные признаки имеют сильно отличающиеся диапазоны значений, то применяют масштабирование исходных данных.

In [50]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

data_full = pd.read_csv('data/dataset.csv', sep=",")
data_full

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,Female,21,1.62,64.00,yes,no,2.0,3.0,Sometimes,no,2.00,no,0.00,1.000,no,Public_Transportation,Normal_Weight
1,Female,21,1.52,56.00,yes,no,3.0,3.0,Sometimes,yes,3.00,yes,3.00,0.000,Sometimes,Public_Transportation,Normal_Weight
2,Male,23,1.80,77.00,yes,no,2.0,3.0,Sometimes,no,2.00,no,2.00,1.000,Frequently,Public_Transportation,Normal_Weight
3,Male,27,1.80,87.00,no,no,3.0,3.0,Sometimes,no,2.00,no,2.00,0.000,Frequently,Walking,Overweight_Level_I
4,Male,22,1.78,89.80,no,no,2.0,1.0,Sometimes,no,2.00,no,0.00,0.000,Sometimes,Public_Transportation,Overweight_Level_II
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,Female,21,1.71,131.41,yes,yes,3.0,3.0,Sometimes,no,1.73,no,1.68,0.906,Sometimes,Public_Transportation,Obesity_Type_III
2107,Female,22,1.75,133.74,yes,yes,3.0,3.0,Sometimes,no,2.01,no,1.34,0.599,Sometimes,Public_Transportation,Obesity_Type_III
2108,Female,23,1.75,133.69,yes,yes,3.0,3.0,Sometimes,no,2.05,no,1.41,0.646,Sometimes,Public_Transportation,Obesity_Type_III
2109,Female,24,1.74,133.35,yes,yes,3.0,3.0,Sometimes,no,2.85,no,1.14,0.586,Sometimes,Public_Transportation,Obesity_Type_III
2110,Female,24,1.74,133.47,yes,yes,3.0,3.0,Sometimes,no,2.86,no,1.03,0.714,Sometimes,Public_Transportation,Obesity_Type_III

Проверим датасет на пустые значения.

In [51]:
# проверим есть ли пропущенные значения
data_full.isnull().sum()

Gender                            0
Age                               0
Height                            0
Weight                            0
family_history_with_overweight    0
FAVC                              0
FCVC                              0
NCP                               0
CAEC                              0
SMOKE                             0
CH2O                              0
SCC                               0
FAF                               0
TUE                               0
CALC                              0
MTRANS                            0
NObeyesdad                        0
dtype: int64

Заметим, что NObeyesdad является категориальным признаком, рассмотрим уникальные значения для него:

In [52]:
np.unique(data_full[['NObeyesdad']])

array(['Insufficient_Weight', 'Normal_Weight', 'Obesity_Type_I',
       'Obesity_Type_II', 'Obesity_Type_III', 'Overweight_Level_I',
       'Overweight_Level_II'], dtype=object)

Создадим регрессионный целевой признак BMI.

In [53]:
def class_to_regr(height:float, weight: float) -> float:
    result = weight/(np.square(height))
    return result

In [54]:
data_full['BMI'] = \
data_full.apply(lambda row: class_to_regr(row['Height'],row['Weight']),axis=1)

Разделим выборку на тестовую и тренировочную.

In [55]:
X = data_full.drop(columns=['NObeyesdad'])  # Let's say column 'target' is the target\class\label column
y = data_full['NObeyesdad']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,
                                                    train_size=0.5, 
                                                    random_state=42)

In [56]:
data_train_to_csv=X_train
data_train_to_csv['NObeyesdad']=y_train
data_train_to_csv

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,BMI,NObeyesdad
162,Female,21,1.63,60.00,yes,yes,3.00,3.00,Always,yes,2.00,no,2.00,0.000,Sometimes,Public_Transportation,22.582709,Normal_Weight
2001,Female,21,1.75,133.62,yes,yes,3.00,3.00,Sometimes,no,2.89,no,1.48,0.780,Sometimes,Public_Transportation,43.631020,Obesity_Type_III
1435,Female,23,1.66,82.60,yes,yes,1.20,1.36,Sometimes,no,2.77,no,0.13,1.659,Sometimes,Public_Transportation,29.975323,Obesity_Type_I
649,Female,22,1.59,44.24,no,no,3.00,1.70,Frequently,no,2.55,no,1.10,0.000,no,Public_Transportation,17.499308,Insufficient_Weight
1280,Male,26,1.81,106.04,yes,yes,3.00,3.00,Sometimes,no,2.86,no,1.81,0.680,Sometimes,Public_Transportation,32.367754,Obesity_Type_I
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
734,Male,18,1.71,51.31,yes,yes,1.30,3.00,Sometimes,no,1.76,no,0.06,1.673,Sometimes,Public_Transportation,17.547280,Insufficient_Weight
717,Male,18,1.85,59.21,yes,yes,2.71,3.74,Sometimes,no,2.03,no,2.01,0.614,no,Automobile,17.300219,Insufficient_Weight
454,Female,20,1.68,68.00,no,yes,3.00,1.00,Sometimes,no,1.00,no,1.00,0.000,no,Public_Transportation,24.092971,Normal_Weight
264,Male,18,1.87,67.00,yes,yes,3.00,3.00,Frequently,no,3.00,yes,1.00,1.000,Sometimes,Automobile,19.159827,Normal_Weight
75,Female,23,1.63,45.00,yes,no,3.00,3.00,Sometimes,no,3.00,yes,2.00,0.000,no,Public_Transportation,16.937032,Insufficient_Weight

In [57]:
data_test_to_csv=X_test
data_test_to_csv

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,BMI
544,Female,20,1.76,53.70,yes,yes,2.00,3.89,Frequently,no,1.86,no,2.87,2.000,no,Public_Transportation,17.336002
1987,Female,26,1.62,111.00,yes,yes,3.00,3.00,Sometimes,no,2.70,no,0.00,0.323,Sometimes,Public_Transportation,42.295382
420,Male,18,1.85,60.00,yes,yes,3.00,4.00,Sometimes,no,2.00,yes,2.00,0.000,Sometimes,Automobile,17.531045
527,Female,21,1.52,42.00,no,yes,3.00,1.00,Frequently,no,1.00,no,0.00,0.000,Sometimes,Public_Transportation,18.178670
196,Male,22,1.75,74.00,yes,no,2.00,3.00,Sometimes,no,2.00,no,1.00,2.000,Sometimes,Bike,24.163265
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
447,Male,19,1.80,87.00,yes,yes,2.00,4.00,Sometimes,no,2.00,no,2.00,1.000,Sometimes,Public_Transportation,26.851852
1793,Male,31,1.65,101.14,yes,yes,2.91,2.27,Sometimes,no,1.00,no,1.89,0.379,no,Public_Transportation,37.149679
73,Male,19,1.85,65.00,yes,no,2.00,3.00,Sometimes,no,3.00,no,2.00,1.000,Sometimes,Bike,18.991965
1711,Male,29,1.76,113.50,yes,yes,2.32,3.00,Sometimes,no,2.16,no,0.00,1.465,Sometimes,Automobile,36.641271
1103,Male,19,1.70,79.68,yes,no,2.74,2.16,Sometimes,no,1.09,no,0.11,0.004,no,Public_Transportation,27.570934

Для второй тестовой выборки возьмем все данные датасета.

In [58]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.99,
                                                    train_size=0.001, 
                                                    random_state=42)
data_test_to_csv2=X_test
data_test_to_csv2

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,BMI
544,Female,20,1.76,53.70,yes,yes,2.00,3.89,Frequently,no,1.86,no,2.87,2.000,no,Public_Transportation,17.336002
1987,Female,26,1.62,111.00,yes,yes,3.00,3.00,Sometimes,no,2.70,no,0.00,0.323,Sometimes,Public_Transportation,42.295382
420,Male,18,1.85,60.00,yes,yes,3.00,4.00,Sometimes,no,2.00,yes,2.00,0.000,Sometimes,Automobile,17.531045
527,Female,21,1.52,42.00,no,yes,3.00,1.00,Frequently,no,1.00,no,0.00,0.000,Sometimes,Public_Transportation,18.178670
196,Male,22,1.75,74.00,yes,no,2.00,3.00,Sometimes,no,2.00,no,1.00,2.000,Sometimes,Bike,24.163265
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
562,Female,17,1.58,44.41,no,yes,2.74,3.00,Sometimes,no,2.31,no,2.24,1.593,Sometimes,Public_Transportation,17.789617
189,Female,33,1.63,62.00,yes,yes,2.00,3.00,Sometimes,no,2.00,no,1.00,1.000,no,Public_Transportation,23.335466
1806,Female,26,1.68,109.90,yes,yes,3.00,3.00,Sometimes,no,1.47,no,0.14,0.445,Sometimes,Public_Transportation,38.938492
975,Female,18,1.73,75.97,yes,yes,2.93,3.00,Sometimes,no,2.21,no,1.00,0.797,Frequently,Public_Transportation,25.383407
2047,Female,19,1.68,127.43,yes,yes,3.00,3.00,Sometimes,no,1.44,no,1.43,0.662,Sometimes,Public_Transportation,45.149518

Запишем полученные датасеты в .csv и запишем в новые переменные (для чистоты эксперимента).

In [59]:
pd.DataFrame.to_csv(data_test_to_csv, './data/obesity_test.csv', sep=",", index=False)
pd.DataFrame.to_csv(data_train_to_csv, './data/obesity_train.csv', sep=",", index=False)
pd.DataFrame.to_csv(data_test_to_csv2, './data/obesity_test_full.csv', sep=",", index=False)